from rest_framework_simplejwt.views import TokenObtainPairView
from api.domain.custom_token_obtain_serializer import CustomTokenObtainPairSerializer

class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairSerializer
