# Generated by Django 4.2.3 on 2024-08-08 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdopterModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        max_length=8,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PetModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                ("race", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("dog", "Dog"), ("cat", "Cat")], max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("adopted", "Adopted"),
                            ("in_adoption", "In Adoption"),
                            ("awaiting_adoption", "Awaiting Adoption"),
                        ],
                        max_length=17,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        max_length=8,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdoptionModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("adoption_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("done", "Done"), ("in_progress", "In Progress")],
                        max_length=12,
                    ),
                ),
                (
                    "adopted_pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.petmodel"
                    ),
                ),
                (
                    "adopter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.adoptermodel",
                    ),
                ),
            ],
        ),
    ]
