from rest_framework_simplejwt.views import TokenObtainPairView
from backend.api.custom_token_obtain_serializer import CustomTokenObtainPairSerializer

class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairSerializer
